extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

settings:
  import/resolver:
    typescript: {}

root: true

rules:
  quotes:
    - 'error'
    - 'single'
  no-unused-vars:
    - 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - 'varsIgnorePattern': '^_'
